stages:
  - check
  - build
  - test
  - package
  - deploy
  - cleanup

check:
  stage: check
  script:
    - ls -al

build:
  stage: build
  script:
    - echo "build"

test:
  stage: test
  script:
    - echo "test"

package:
  stage: package
  script:
    - echo "packaging..."

build image:
  stage: package
  script:
    - echo "build docker image..."

deploy:
  stage: deploy
  script:
    - echo "deploying..."

clean:
  stage: cleanup
  script:
    - rm -rf *
