image: node:21
debug:
  stage: .pre
  script:
    - env

stages:
  - install
  - build
  - test
  - package
  - deploy

variables:
  NODE_ENV: production

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

build:
  variables:
    PROJET_GROUP: simachille
    PROJET_NAME: front-imc
    PROJET_VERSION: latest
  stage: build
  script:
 
    - npm run build
    - npm run export
    - mkdir -p dist
    - cp -r out/* dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - docker build -t $PROJET_GROUP/$PROJET_NAME:$PROJET_VERSION .

deploy:
  stage: deploy
  script:
    - echo "Déploiement en cours..."
