image: node:21

stages:
  - install
  - build
  - test
  - package
  - deploy

variables:
  NODE_ENV: production

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

build:
  stage: build
  script:
    - npm run build
    - npm run export
    - mkdir -p dist
    - cp -r out/* dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - docker build -t simachille/front-imc:latest .

deploy:
  stage: deploy
  script:
    - echo "Déploiement en cours..."
